void vshader(
  float4 vtx_position : POSITION,
  out float4 l_position : POSITION,
  float2 vtx_texcoord0 : TEXCOORD0,
  out float2 l_texcoord0 : TEXCOORD0,
  uniform float4x4 mat_modelproj)
{
  l_position = mul(mat_modelproj, vtx_position);
  l_texcoord0 = vtx_texcoord0;
}
 
void fshader(
  uniform sampler2D tex_0,
  uniform sampler2D timer_tex,
  uniform float4 timer_frame,
  float2 l_texcoord0 : TEXCOORD0,
  uniform float4 attr_color,
  out float4 o_color : COLOR) 
{
  float4 timer = tex2D(timer_tex, timer_frame.xy + timer_frame.zw * l_texcoord0);
  float4 color = tex2D(tex_0, l_texcoord0) * attr_color;
  o_color = float4(color.rgb * color.a + timer.rgb * timer.a, timer.a+color.a);
}
